CREATE TABLE Questions (id serial PRIMARY KEY,text VARCHAR(10000) NOT NULL);
CREATE TABLE Answers (answer serial PRIMARY KEY,text VARCHAR(10000));
CREATE TABLE Users (userid serial PRIMARY KEY,name VARCHAR(10000) NOT NULL,surname VARCHAR(10000) NOT NULL, age INTEGER);
INSERT INTO Questions (text) VALUES ('1. Я люблю читать научно-техническую литературу ');
INSERT INTO Questions (text) VALUES ('2. у меня хороший аппетит ');
INSERT INTO Questions (text) VALUES ('3. по утрам я обычно встаю свежим и отдохнувшим ');
INSERT INTO Questions (text) VALUES ('4. думаю, что мне понравилась бы работа библиотекаря ');
INSERT INTO Questions (text) VALUES ('5. малейший шум меня будит ');
INSERT INTO Questions (text) VALUES ('6. я люблю читать в газетах заметки о преступлениях ');
INSERT INTO Questions (text) VALUES ('7. мои руки и ноги обычно достаточно теплые ');
INSERT INTO Questions (text) VALUES ('8. моя повседневная жизнь полна событий, интересующих меня ');
INSERT INTO Questions (text) VALUES ('9. моя работоспособность не хуже, чем была раньше ');
INSERT INTO Questions (text) VALUES ('10. я часто ощущаю "комок" в горле ');
INSERT INTO Questions (text) VALUES ('11. я верю, что сны всегда сбываются ');
INSERT INTO Questions (text) VALUES ('12. я люблю читать о преступлениях и таинственных приключениях ');
INSERT INTO Questions (text) VALUES ('13. работа дается мне ценой значительного напряжения ');
INSERT INTO Questions (text) VALUES ('14. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('15. временами мне в голову приходят такие нехорошие мысли, что о них лучше не рассказывать ');
INSERT INTO Questions (text) VALUES ('16. я считаю, что жизнь ко мне беспощадна ');
INSERT INTO Questions (text) VALUES ('17. мой отец - хороший человек ');
INSERT INTO Questions (text) VALUES ('18. у меня очень редко бывают запоры ');
INSERT INTO Questions (text) VALUES ('19. поступая на новую работу, я предпочитаю знать, с кем я должен наладить хорошие отношения ');
INSERT INTO Questions (text) VALUES ('20. моя половая жизнь удовлетворительна ');
INSERT INTO Questions (text) VALUES ('21. временами мне очень хотелось покинуть дом ');
INSERT INTO Questions (text) VALUES ('22. временами у меня бывают приступы смеха или плача, которые я не могу контролировать ');
INSERT INTO Questions (text) VALUES ('23. меня беспокоят приступы тошноты и рвоты ');
INSERT INTO Questions (text) VALUES ('24. мне кажется, что нет такого человека, который понимал бы меня ');
INSERT INTO Questions (text) VALUES ('25. я бы хотел быть певцом ');
INSERT INTO Questions (text) VALUES ('26. если я попадаю в неприятное положение, то мне лучше всего держать язык за зубами ');
INSERT INTO Questions (text) VALUES ('27. временами я нахожусь во власти какой-то злой силы ');
INSERT INTO Questions (text) VALUES ('28. если со мной поступают несправедливо, я чувствую, что должен отплатить за это просто из принципа ');
INSERT INTO Questions (text) VALUES ('29. несколько раз в неделю меня беспокоит изжога ');
INSERT INTO Questions (text) VALUES ('30. иногда мне хочется выругаться ');
INSERT INTO Questions (text) VALUES ('31. кошмарные сны снятся мне почти каждую ночь ');
INSERT INTO Questions (text) VALUES ('32. я замечаю, что мне трудно стало сосредоточиться на определенной задаче или работе ');
INSERT INTO Questions (text) VALUES ('33. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('34. большую часть времени у меня бывает кашель ');
INSERT INTO Questions (text) VALUES ('35. если бы люди не интриговали против меня, я бы добился гораздо большего ');
INSERT INTO Questions (text) VALUES ('36. я редко беспокоюсь о своем здоровье ');
INSERT INTO Questions (text) VALUES ('37. у меня никогда не было неприятностей из-за моего поведения, связанного с половой жизнью ');
INSERT INTO Questions (text) VALUES ('38. в юности было время, когда я совершал мелкие кражи ');
INSERT INTO Questions (text) VALUES ('39. временами мне хочется ломать вещи, бить посуду ');
INSERT INTO Questions (text) VALUES ('40. я бы предпочел большую часть времени сидеть ничего не делая и мечтать ');
INSERT INTO Questions (text) VALUES ('41. у меня бывали такие периоды, тянувшиеся дни, недели или даже месяцы, когда я не мог ни за что взяться, т.к. не мог включиться в работу ');
INSERT INTO Questions (text) VALUES ('42. моей семье не нравится работа, которую я выбрал (или собираюсь выбрать) ');
INSERT INTO Questions (text) VALUES ('43. у меня прерывистый и беспокойный сон ');
INSERT INTO Questions (text) VALUES ('44. большую часть времени у меня болит голова ');
INSERT INTO Questions (text) VALUES ('45. я не всегда говорю правду ');
INSERT INTO Questions (text) VALUES ('46. мой рассудок работает сейчас лучше, чем когда-либо ');
INSERT INTO Questions (text) VALUES ('47. раз в неделю или чаще меня без видимой причины неожиданно "обдает жаром" ');
INSERT INTO Questions (text) VALUES ('48. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('49. было бы лучше, если бы почти все законы отменили ');
INSERT INTO Questions (text) VALUES ('50. временами я чувствую, что умираю ');
INSERT INTO Questions (text) VALUES ('51. мое физическое здоровье не хуже, чем у большинства моих знакомых ');
INSERT INTO Questions (text) VALUES ('52. я предпочитаю проходить мимо своих школьных друзей или людей, которых я давно видел, если они со мной не заговаривают первыми ');
INSERT INTO Questions (text) VALUES ('53. я верю, что прикосновением руки и молитвой можно вылечить болезнь ');
INSERT INTO Questions (text) VALUES ('54. большинство знающих меня людей относятся ко мне хорошо ');
INSERT INTO Questions (text) VALUES ('55. меня редко беспокоят боли в сердце или груди ');
INSERT INTO Questions (text) VALUES ('56. когда я был мальчишкой, меня выгоняли из школы за прогулы ');
INSERT INTO Questions (text) VALUES ('57. я - человек общительный ');
INSERT INTO Questions (text) VALUES ('58. все, что предстоит человечеству, давно уже предначертано ');
INSERT INTO Questions (text) VALUES ('59. мне часто приходилось выполнять указания лиц, знавших меньше меня ');
INSERT INTO Questions (text) VALUES ('60. я не каждый день читаю передовицы в газетах ');
INSERT INTO Questions (text) VALUES ('61. я вел неправильный образ жизни ');
INSERT INTO Questions (text) VALUES ('62. я часто чувствую жжение, покалывание или онемение в различных частях своего тела ');
INSERT INTO Questions (text) VALUES ('63. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('64. временами я так настаиваю на своем, что окружающие теряют терпение ');
INSERT INTO Questions (text) VALUES ('65. я люблю (любил) своего отца ');
INSERT INTO Questions (text) VALUES ('66. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('67. другие мне кажутся счастливее меня ');
INSERT INTO Questions (text) VALUES ('68. у меня почти никогда не бывает болей в области шеи и затылка ');
INSERT INTO Questions (text) VALUES ('69. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('70. мне нравилось играть в "садовника"или "колечко" (т.е. такие игры, где мальчики и девочки выбирали друг друга, исходя из личных симпатий) ');
INSERT INTO Questions (text) VALUES ('71. думаю, что многие преувеличивают свои несчастья, чтобы добиться сочувствия и помощи ');
INSERT INTO Questions (text) VALUES ('72. несколько раз в неделю или чаще меня беспокоят неприятные ощущения в верхней части живота(под ложечкой) ');
INSERT INTO Questions (text) VALUES ('73. я - значительная личность ');
INSERT INTO Questions (text) VALUES ('74. иногда я думаю: "лучше бы я родился женщиной" ');
INSERT INTO Questions (text) VALUES ('75. иногда я бываю сердитым ');
INSERT INTO Questions (text) VALUES ('76. большую часть времени у меня подавленное настроение ');
INSERT INTO Questions (text) VALUES ('77. я люблю читать о любви ');
INSERT INTO Questions (text) VALUES ('78. я люблю поэзию ');
INSERT INTO Questions (text) VALUES ('79. меня не так легко задеть /я не обидчив/ ');
INSERT INTO Questions (text) VALUES ('80. иногда я дразню животных ');
INSERT INTO Questions (text) VALUES ('81. думаю, мне понравилась бы работа лесничего ');
INSERT INTO Questions (text) VALUES ('82. меня легко переубедить ');
INSERT INTO Questions (text) VALUES ('83. любой, кто может и хочет усердно трудиться, имеет хорошую возможность добиться успеха ');
INSERT INTO Questions (text) VALUES ('84. чувствую, что я теряю надежду добиться чего-либо в жизни ');
INSERT INTO Questions (text) VALUES ('85. иногда меня так привлекают чужие вещи (перчатки, туфли и т.д.),что мне хочется украсть их, хотя они мне не нужны ');
INSERT INTO Questions (text) VALUES ('86. мне безусловно не хватает уверенности в себе ');
INSERT INTO Questions (text) VALUES ('87. мне бы понравилось заниматься разведением цветов ');
INSERT INTO Questions (text) VALUES ('88. я считаю, что жизнь стоит того, чтобы жить ');
INSERT INTO Questions (text) VALUES ('89. нужно множество доказательств, чтобы убедить людей в какой-либо истине ');
INSERT INTO Questions (text) VALUES ('90. иногда я откладываю на завтра, то что должен сделать сегодня ');
INSERT INTO Questions (text) VALUES ('91. я не против того, чтобы меня выбирали мишенью для насмешек ');
INSERT INTO Questions (text) VALUES ('92. мне бы понравилось работать няней /ухаживать за больными/ ');
INSERT INTO Questions (text) VALUES ('93. я считаю, что большинство людей способно солгать, если это в их интересах ');
INSERT INTO Questions (text) VALUES ('94. я часто совершаю поступки, о которых потом сожалею (больше и чаще, чем другие) ');
INSERT INTO Questions (text) VALUES ('95. я регулярно принимаю участие в собраниях и других общественных мероприятиях ');
INSERT INTO Questions (text) VALUES ('96. я очень редко ссорюсь с членами моей семьи ');
INSERT INTO Questions (text) VALUES ('97. временами я испытываю непреодолимую потребность причинить кому-нибудь вред или сделать что-либо неприличное ');
INSERT INTO Questions (text) VALUES ('98. я верю, что в конце концов справедливость восторжествует ');
INSERT INTO Questions (text) VALUES ('99. я люблю ходить в гости или в другие места, где бывает много шумных забав ');
INSERT INTO Questions (text) VALUES ('100. я встречал проблемы с таким множеством решений, что мне трудно было остановиться на одном из них ');
INSERT INTO Questions (text) VALUES ('101. я считаю, что женщина в половом отношении должна иметь такую же свободу, как и мужчина ');
INSERT INTO Questions (text) VALUES ('102. самая трудная борьба для меня - борьба с самим собой ');
INSERT INTO Questions (text) VALUES ('103. у меня очень редко бывают мышечные судороги или подергивания /или не бывает совсем/ ');
INSERT INTO Questions (text) VALUES ('104. у меня нет оснований беспокоиться о том, что со мной будет ');
INSERT INTO Questions (text) VALUES ('105. иногда, когда я себя плохо чувствую, я бываю раздражительным ');
INSERT INTO Questions (text) VALUES ('106. большую часть времени у меня такое чувство, как- будто я сделал что-то плохое или злое ');
INSERT INTO Questions (text) VALUES ('107. большую часть времени я чувствую себя счастливым ');
INSERT INTO Questions (text) VALUES ('108. я почти все время испытываю чувство заполненности в голове или в носу ');
INSERT INTO Questions (text) VALUES ('109. некоторые люди так любят командовать, что мне хочется все сделать наоборот, даже если я знаю, что они правы ');
INSERT INTO Questions (text) VALUES ('110. я знаю, что есть люди, настроенные против меня ');
INSERT INTO Questions (text) VALUES ('111. я никогда не шел на опасное дело ради сильных впечатлений ');
INSERT INTO Questions (text) VALUES ('112. я часто нахожу необходимым отстаивать то, что считаю правильным ');
INSERT INTO Questions (text) VALUES ('113. я понимаю, как важны законы ');
INSERT INTO Questions (text) VALUES ('114. я часто чувствую, что голова как- бы стянута обручем ');
INSERT INTO Questions (text) VALUES ('115. я верю в справедливость ');
INSERT INTO Questions (text) VALUES ('116. я получаю больше удовольствия от игры или скачек, если держу пари ');
INSERT INTO Questions (text) VALUES ('117. большинство людей честны только потому, что боятся наказания ');
INSERT INTO Questions (text) VALUES ('118. в школе меня иногда вызывали к директору за прогулы ');
INSERT INTO Questions (text) VALUES ('119. моя речь такая же, как всегда (не быстрее, не медленнее, без хрипоты и затруднений в произношении) ');
INSERT INTO Questions (text) VALUES ('120. мои манеры за столом у себя дома не так хороши, как в гостях ');
INSERT INTO Questions (text) VALUES ('121. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('122. по-видимому, я также способен и сообразителен, как и большинство других окружающих меня людей ');
INSERT INTO Questions (text) VALUES ('123. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('124. я считаю, что большинство людей ради выгоды скорее поступят нечестно, чем упустят случай ');
INSERT INTO Questions (text) VALUES ('125. меня очень беспокоит мой желудок ');
INSERT INTO Questions (text) VALUES ('126. мне нравится драматургия ');
INSERT INTO Questions (text) VALUES ('127. я знаю, кто виноват в большинстве моих неприятностей /не имея в виду себя/ ');
INSERT INTO Questions (text) VALUES ('128. при виде крови я не пугаюсь и мне не становится дурно ');
INSERT INTO Questions (text) VALUES ('129. часто я не могу понять, почему я был таким упрямым и ворчливым ');
INSERT INTO Questions (text) VALUES ('130. у меня никогда не было кровавой рвоты или кашля с кровью ');
INSERT INTO Questions (text) VALUES ('131. меня не тревожит возможность заразиться какой-нибудь болезнью ');
INSERT INTO Questions (text) VALUES ('132. я люблю собирать цветы или выращивать комнатные растения ');
INSERT INTO Questions (text) VALUES ('133. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('134. временами мои мысли текут быстрее, чем я успеваю их высказывать ');
INSERT INTO Questions (text) VALUES ('135. я перехожу улицу в неположенном месте, если уверен, что меня не заметит милиционер ');
INSERT INTO Questions (text) VALUES ('136. если мне делают что-то приятное, меня обычно интересует, что за этим кроется ');
INSERT INTO Questions (text) VALUES ('137. я считаю, что в моем доме жизнь идет не хуже, чем у большинства моих знакомых ');
INSERT INTO Questions (text) VALUES ('138. критика и замечания очень задевают меня ');
INSERT INTO Questions (text) VALUES ('139. иногда я чувствую, что должен нанести повреждение или самому себе, или кому-нибудь другому ');
INSERT INTO Questions (text) VALUES ('140. я люблю готовить еду ');
INSERT INTO Questions (text) VALUES ('141. мое поведение в значительной мере определяется правилами и привычками окружающих меня людей ');
INSERT INTO Questions (text) VALUES ('142. временами я уверен в собственной бесполезности ');
INSERT INTO Questions (text) VALUES ('143. в детстве я был в такой компании, где все во всем стояли друг за друга ');
INSERT INTO Questions (text) VALUES ('144. мне нравится солдатская служба ');
INSERT INTO Questions (text) VALUES ('145. временами меня так и подмывает вступить с кем-нибудь в драку ');
INSERT INTO Questions (text) VALUES ('146. у меня страсть к перемене мест, и я не могу быть счастлив без путешествий и странствий ');
INSERT INTO Questions (text) VALUES ('147. я часто многое теряю из-за того, что не могу достаточно быстро принять решение ');
INSERT INTO Questions (text) VALUES ('148. я теряю терпение с людьми, которые обращаются за советом или как-нибудь иначе отвлекают меня во время серьезной работы ');
INSERT INTO Questions (text) VALUES ('149. я вел дневник ');
INSERT INTO Questions (text) VALUES ('150. в игре мне приятнее выигрывать, чем проигрывать ');
INSERT INTO Questions (text) VALUES ('151. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('152. большей частью я засыпаю без тревожных мыслей ');
INSERT INTO Questions (text) VALUES ('153. последние несколько лет мое самочувствие большую часть времени хорошее ');
INSERT INTO Questions (text) VALUES ('154. у меня никогда не было припадков или судорог ');
INSERT INTO Questions (text) VALUES ('155. у меня довольно постоянный вес ');
INSERT INTO Questions (text) VALUES ('156. у меня бывают такие состояния, когда я не осознаю, что делаю ');
INSERT INTO Questions (text) VALUES ('157. я считаю, что меня часто незаслуженно наказывали ');
INSERT INTO Questions (text) VALUES ('158. я легко могу заплакать ');
INSERT INTO Questions (text) VALUES ('159. я стал хуже понимать содержание прочитанного ');
INSERT INTO Questions (text) VALUES ('160. я сейчас чувствую себя лучше, чем когда-либо в жизни ');
INSERT INTO Questions (text) VALUES ('161. теменная часть головы у меня иногда бывает очень чувствительной ');
INSERT INTO Questions (text) VALUES ('162. я бываю возмущен и раздражен, когда приходится признать, что меня умело провели ');
INSERT INTO Questions (text) VALUES ('163. я бы не сказал, что я быстро устаю /я не устаю-верно/ ');
INSERT INTO Questions (text) VALUES ('164. мне нравится читать литературу по своей специальности ');
INSERT INTO Questions (text) VALUES ('165. мне нравится иметь значительных людей среди моих знакомых, так как это повышает мой престиж ');
INSERT INTO Questions (text) VALUES ('166. мне страшно смотреть вниз с высоты ');
INSERT INTO Questions (text) VALUES ('167. меня бы не стало волновать, если бы кто-нибудь из членов моей семьи оказался в положении нарушившего закон ');
INSERT INTO Questions (text) VALUES ('168. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('169. я не боюсь иметь дело с деньгами ');
INSERT INTO Questions (text) VALUES ('170. меня не беспокоит, что обо мне говорят другие ');
INSERT INTO Questions (text) VALUES ('171. мне бывает неудобно дурачиться на вечеринке, даже если все остальные это делают ');
INSERT INTO Questions (text) VALUES ('172. мне часто приходится скрывать свою застенчивость ценой больших усилий ');
INSERT INTO Questions (text) VALUES ('173. я любил школу /для учащихся люблю/ ');
INSERT INTO Questions (text) VALUES ('174. я никогда не падал в обморок ');
INSERT INTO Questions (text) VALUES ('175. у меня не бывает головокружения (или бывает очень редко) ');
INSERT INTO Questions (text) VALUES ('176. я бы не сказал, что очень боюсь змей ');
INSERT INTO Questions (text) VALUES ('177. моя мать - хорошая женщина ');
INSERT INTO Questions (text) VALUES ('178. с памятью у меня все благополучно ');
INSERT INTO Questions (text) VALUES ('179. я обеспокоен некоторыми вопросами, связанными с половой жизнью ');
INSERT INTO Questions (text) VALUES ('180. мне трудно поддерживать разговор с людьми, с которыми я только что познакомился ');
INSERT INTO Questions (text) VALUES ('181. когда мне скучно, я стараюсь устроить что-нибудь веселое ');
INSERT INTO Questions (text) VALUES ('182. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('183. я против того, чтобы подавать милостыню ');
INSERT INTO Questions (text) VALUES ('184. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('185. мой слух не хуже, чем у большинства людей ');
INSERT INTO Questions (text) VALUES ('186. я замечаю, что мои руки дрожат, когда я пытаюсь что-нибудь делать ');
INSERT INTO Questions (text) VALUES ('187. мои руки не стали неловкими ');
INSERT INTO Questions (text) VALUES ('188. я могу долго читать без заметного утомления глаз ');
INSERT INTO Questions (text) VALUES ('189. большую часть времени я чувствую слабость ');
INSERT INTO Questions (text) VALUES ('190. у меня очень редко болит голова ');
INSERT INTO Questions (text) VALUES ('191. иногда, когда я смущаюсь, я обливаюсь потом и мне это очень неприятно ');
INSERT INTO Questions (text) VALUES ('192. мне не трудно сохранять равновесие при ходьбе ');
INSERT INTO Questions (text) VALUES ('193. у меня не бывает приступов лихорадки или астмы ');
INSERT INTO Questions (text) VALUES ('194. у меня бывали приступы, во время которых я не управлял своими движениями и речью, но понимал, что происходит вокруг ');
INSERT INTO Questions (text) VALUES ('195. не все, кого я знаю, мне нравятся ');
INSERT INTO Questions (text) VALUES ('196. я люблю посещать места, где никогда не бывал раньше ');
INSERT INTO Questions (text) VALUES ('197. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('198. я предаюсь мечтам не часто ');
INSERT INTO Questions (text) VALUES ('199. детей следует учить правильному представлению об основных вопросах половой жизни ');
INSERT INTO Questions (text) VALUES ('200. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('201. я бы хотел быть не таким застенчивым ');
INSERT INTO Questions (text) VALUES ('202. я считаю себя обреченным человеком ');
INSERT INTO Questions (text) VALUES ('203. если бы я был журналистом, мне бы понравилось писать о театре ');
INSERT INTO Questions (text) VALUES ('204. мне бы понравилось быть журналистом ');
INSERT INTO Questions (text) VALUES ('205. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('206. я строго придерживаюсь принципов нравственности и морали, гораздо больше всех окружающих меня людей ');
INSERT INTO Questions (text) VALUES ('207. я люблю разные игры и развлечения ');
INSERT INTO Questions (text) VALUES ('208. мне нравится флиртовать (вести игривый разговор с нравящейся мне женщиной или девушкой) ');
INSERT INTO Questions (text) VALUES ('209. я уверен, что моим проступкам нет прощения ');
INSERT INTO Questions (text) VALUES ('210. вся пища мне кажется одинаковой на вкус ');
INSERT INTO Questions (text) VALUES ('211. мне хочется спать днем, а ночью я страдаю от бессоницы ');
INSERT INTO Questions (text) VALUES ('212. мои родные обращаются со мной как с ребенком, а не как со взрослым ');
INSERT INTO Questions (text) VALUES ('213. при ходьбе я очень осторожно перешагиваю через трещины в тротуаре ');
INSERT INTO Questions (text) VALUES ('214. у меня никогда не было каких-либо высыпаний на коже, которые бы меня тревожили ');
INSERT INTO Questions (text) VALUES ('215. я чрезмерно увлекался алкогольными напитками ');
INSERT INTO Questions (text) VALUES ('216. в моем доме отношения менее теплые и дружеские, чем в других семьях ');
INSERT INTO Questions (text) VALUES ('217. я часто замечаю за собой, что тревожусь о чем-то ');
INSERT INTO Questions (text) VALUES ('218. меня не особенно трогает вид страдающего животного ');
INSERT INTO Questions (text) VALUES ('219. думаю, мне бы понравилась работа, связанная с материальным снабжением больших организаций ');
INSERT INTO Questions (text) VALUES ('220. я люблю свою мать ');
INSERT INTO Questions (text) VALUES ('221. меня интересует наука ');
INSERT INTO Questions (text) VALUES ('222. мне не трудно просить об услуге моих друзей, даже если я не могу ответить им тем же ');
INSERT INTO Questions (text) VALUES ('223. я очень люблю охоту ');
INSERT INTO Questions (text) VALUES ('224. мои родители часто не одобряли моих знакомств ');
INSERT INTO Questions (text) VALUES ('225. иногда я могу немного посплетничать ');
INSERT INTO Questions (text) VALUES ('226. у некоторых членов моей семьи есть привычки, которые меня очень раздражают и надоедают мне ');
INSERT INTO Questions (text) VALUES ('227. мне говорили, что я хожу во сне ');
INSERT INTO Questions (text) VALUES ('228. временами я чувствую, что мне необыкновенно легко принимать решения ');
INSERT INTO Questions (text) VALUES ('229. я бы охотно записался в несколько разных кружков и обществ ');
INSERT INTO Questions (text) VALUES ('230. я почти никогда не замечал у себя приступов сердцебиения или одышки ');
INSERT INTO Questions (text) VALUES ('231. я люблю поговорить на темы, связанные с вопросами пола ');
INSERT INTO Questions (text) VALUES ('232. я наметил себе жизненную программу, основанную на чувстве долга и ответственности, и стараюсь ее выполнять ');
INSERT INTO Questions (text) VALUES ('233. иногда я не уступаю людям не потому, что дело действительно важное, а просто из принципа ');
INSERT INTO Questions (text) VALUES ('234. я легко выхожу из себя, но быстро успокаиваюсь ');
INSERT INTO Questions (text) VALUES ('235. я всегда был вполне независим и свободен от принятых в нашей семье правил и традиций ');
INSERT INTO Questions (text) VALUES ('236. я слишком часто предаюсь размышлениям ');
INSERT INTO Questions (text) VALUES ('237. почти все мои родственники относятся ко мне хорошо ');
INSERT INTO Questions (text) VALUES ('238. у меня бывают периоды такого сильного беспокойства, когда я не могу долго усидеть на одном месте ');
INSERT INTO Questions (text) VALUES ('239. я испытал разочарование в любви ');
INSERT INTO Questions (text) VALUES ('240. моя внешность никогда не вызывает у меня беспокойства ');
INSERT INTO Questions (text) VALUES ('241. я часто вижу такие сны, о которых лучше умолчать ');
INSERT INTO Questions (text) VALUES ('242. я не считаю себя более нервным, чем большинство окружающих ');
INSERT INTO Questions (text) VALUES ('243. у меня редко что-нибудь болит ');
INSERT INTO Questions (text) VALUES ('244. мои поступки обычно бывают неправильно поняты окружающими ');
INSERT INTO Questions (text) VALUES ('245. мои родители и другие члены семьи часто без всяких оснований ко мне придираются ');
INSERT INTO Questions (text) VALUES ('246. моя шея часто покрывается красными пятнами ');
INSERT INTO Questions (text) VALUES ('247. у меня есть основания испытывать чувство зависти к некоторым членам моей семьи ');
INSERT INTO Questions (text) VALUES ('248. иногда без всякой причины, или даже когда дела идут неважно, я чувствую себя взволнованно-счастливым, "на вершине блаженства" ');
INSERT INTO Questions (text) VALUES ('249. я уверен, что того, кто совершает злые поступки, в будущем ожидает кара ');
INSERT INTO Questions (text) VALUES ('250. я не осуждаю того, кто стремится урвать от жизни все,что только может ');
INSERT INTO Questions (text) VALUES ('251. у меня бывали такие провалы в сознании, когда мои действия были прерваны, и я не понимал, что происходит вокруг меня ');
INSERT INTO Questions (text) VALUES ('252. никому нет дела до того, что с тобой случится ');
INSERT INTO Questions (text) VALUES ('253. я могу дружелюбно относиться к людям, поступки которых я не одобряю ');
INSERT INTO Questions (text) VALUES ('254. мне нравится бывать в компании, где любят подшучивать друг над другом ');
INSERT INTO Questions (text) VALUES ('255. иногда я даю хорошую оценку людям, о которых знаю очень мало ');
INSERT INTO Questions (text) VALUES ('256. наиболее интересная страница в газете - отдел юмора ');
INSERT INTO Questions (text) VALUES ('257. обычно я надеюсь на успех, когда берусь за какое-нибудь дело ');
INSERT INTO Questions (text) VALUES ('258. я верю в торжество справедливости ');
INSERT INTO Questions (text) VALUES ('259. мне очень трудно начать какую бы то ни было работу ');
INSERT INTO Questions (text) VALUES ('260. в школе я плохо усваивал материал ');
INSERT INTO Questions (text) VALUES ('261. будь я художником, мне бы понравилось рисовать цветы ');
INSERT INTO Questions (text) VALUES ('262. моя внешность меня не особенно огорчает ');
INSERT INTO Questions (text) VALUES ('263. у меня повышенная потливость, даже при прохладной погоде ');
INSERT INTO Questions (text) VALUES ('264. я абсолютно уверен в себе ');
INSERT INTO Questions (text) VALUES ('265. безопаснее никому не доверять ');
INSERT INTO Questions (text) VALUES ('266. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('267. когда я нахожусь среди людей, мне трудно подобрать тему для разговора ');
INSERT INTO Questions (text) VALUES ('268. испорченное настроение мне всегда легко исправить чем-нибудь интересным ');
INSERT INTO Questions (text) VALUES ('269. иногда я для забавы пугаю людей,так-как мне легко заставить других бояться меня ');
INSERT INTO Questions (text) VALUES ('270. выйдя из дома, я не волнуюсь о том, закрыта ли дверь, выключен ли газ и т.д. ');
INSERT INTO Questions (text) VALUES ('271. я не осуждаю человека за обман тех, кто легко позволяет себя обманывать ');
INSERT INTO Questions (text) VALUES ('272. временами я бываю полон энергии ');
INSERT INTO Questions (text) VALUES ('273. у меня бывает онемение в некоторых участках кожи ');
INSERT INTO Questions (text) VALUES ('274. мое зрение такое же острое, как и раньше ');
INSERT INTO Questions (text) VALUES ('275. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('276. я люблю детей ');
INSERT INTO Questions (text) VALUES ('277. иногда меня так забавляет ловкость мошенника, что мне хочется, чтобы ему повезло ');
INSERT INTO Questions (text) VALUES ('278. я часто замечал, что незнакомые люди смотрят на меня критически ');
INSERT INTO Questions (text) VALUES ('279. я ежедневно выпиваю необычайно большое количество воды ');
INSERT INTO Questions (text) VALUES ('280. большинство людей заводит знакомства потому, что друзья могут оказаться полезными ');
INSERT INTO Questions (text) VALUES ('281. я редко замечаю у себя шум или звон в ушах ');
INSERT INTO Questions (text) VALUES ('282. временами я испытываю ненависть к членам своей семьи, которых обычно люблю ');
INSERT INTO Questions (text) VALUES ('283. если бы я был журналистом, то предпочел бы писать о спорте ');
INSERT INTO Questions (text) VALUES ('284. я убежден, что являюсь предметом обсуждения ');
INSERT INTO Questions (text) VALUES ('285. бывает, что я смеюсь по поводу вольной /неприличной/ шутки ');
INSERT INTO Questions (text) VALUES ('286. счастливее всего я себя чувствую в одиночестве ');
INSERT INTO Questions (text) VALUES ('287. у меня меньше оснований опасаться чего-либо по сравнению с другими ');
INSERT INTO Questions (text) VALUES ('288. у меня бывают приступы тошноты или рвоты ');
INSERT INTO Questions (text) VALUES ('289. меня возмущает, что преступника по каким-либо причинам могут освободить, и он остается безнаказанным благодаря ловким аргументам адвоката ');
INSERT INTO Questions (text) VALUES ('290. работа дается мне ценой значительного напряжения; работаю с большим напряжением ');
INSERT INTO Questions (text) VALUES ('291. в моей жизни бывали случаи, когда я чувствовал, что кто-то заставляет меня действовать, гипнотизируя меня ');
INSERT INTO Questions (text) VALUES ('292. я предпочитаю не заговаривать с людьми, пока они сами не обратятся ко мне ');
INSERT INTO Questions (text) VALUES ('293. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('294. я никогда не нарушал закона ');
INSERT INTO Questions (text) VALUES ('295. мне нравилось читать сказки андерсена "гадкий утенок","стойкий оловянный солдатик" и др. ');
INSERT INTO Questions (text) VALUES ('296. у меня бывают периоды беспричинной веселости ');
INSERT INTO Questions (text) VALUES ('297. я бы хотел избавиться от мыслей, связанных с половым вопросом, так как они меня беспокоят ');
INSERT INTO Questions (text) VALUES ('298. когда несколько человек попадают в неприятную историю, им лучше условиться, что говорить, а потом всем придерживаться одной линии ');
INSERT INTO Questions (text) VALUES ('299. думаю, что я чувствую более остро, чем большинство людей ');
INSERT INTO Questions (text) VALUES ('300. в моей жизни не было такого периода, когда я любил играть в куклы ');
INSERT INTO Questions (text) VALUES ('301. жизнь для меня большую часть времени связана с напряжением ');
INSERT INTO Questions (text) VALUES ('302. у меня никогда не было неприятностей из-за моего поведения, связанного с вопросами пола /секса/ ');
INSERT INTO Questions (text) VALUES ('303. меня настолько волнуют некоторые темы, что стараюсь не касаться их в разговоре ');
INSERT INTO Questions (text) VALUES ('304. в школьные годы мне было очень трудно говорить перед всем классом ');
INSERT INTO Questions (text) VALUES ('305. даже среди людей я большую часть времени чувствую себя одиноким, даже находясь среди людей ');
INSERT INTO Questions (text) VALUES ('306. я получаю от окружающих столько сочувствия,сколько заслуживаю ');
INSERT INTO Questions (text) VALUES ('307. я отказываюсь играть в некоторые игры из-за того, что неважно играю ');
INSERT INTO Questions (text) VALUES ('308. временами мне очень хотелось покинуть дом ');
INSERT INTO Questions (text) VALUES ('309. мне кажется, что схожусь с людьми так же легко, как и другие ');
INSERT INTO Questions (text) VALUES ('310. моя половая жизнь удовлетворительна ');
INSERT INTO Questions (text) VALUES ('311. в юности было время, когда я совершал мелкие кражи ');
INSERT INTO Questions (text) VALUES ('312. мне неприятно быть среди людей ');
INSERT INTO Questions (text) VALUES ('313. человек, оставляющий свои вещи без присмотра и вводящий этим в искушение, виноват в той же степени, что и вор ');
INSERT INTO Questions (text) VALUES ('314. временами мне в голову приходят такие нехорошие мысли, что о них лучше не рассказывать ');
INSERT INTO Questions (text) VALUES ('315. я считаю, что жизнь ко мне беспощадна ');
INSERT INTO Questions (text) VALUES ('316. думаю, что почти каждый может солгать, чтобы избежать неприятностей ');
INSERT INTO Questions (text) VALUES ('317. я более раним, чем большинство людей ');
INSERT INTO Questions (text) VALUES ('318. моя повседневная жизнь полна событий, интересующих меня ');
INSERT INTO Questions (text) VALUES ('319. большинству людей не нравится поступаться своими интересами ради других ');
INSERT INTO Questions (text) VALUES ('320. мне часто снятся сны на темы, связанные с половой жизнью ');
INSERT INTO Questions (text) VALUES ('321. меня легко ввести в смущение ');
INSERT INTO Questions (text) VALUES ('322. меня беспокоят мои денежные и служебные дела ');
INSERT INTO Questions (text) VALUES ('323. у меня бывали совершенно необычные, очень странные, своеобразные переживания ');
INSERT INTO Questions (text) VALUES ('324. я никогда ни в кого не был влюблен ');
INSERT INTO Questions (text) VALUES ('325. я напуган тем, что совершил кое-кто из членов моей семьи ');
INSERT INTO Questions (text) VALUES ('326. временами у меня бывают приступы смеха или плача, которые я не могу контролировать ');
INSERT INTO Questions (text) VALUES ('327. мне часто приходилось подчиняться родителям, даже тогда, когда они, на мой взгляд, были неправы ');
INSERT INTO Questions (text) VALUES ('328. я замечаю, что мне трудно сосредоточиться на определенной задаче или работе ');
INSERT INTO Questions (text) VALUES ('329. мне редко снятся сны ');
INSERT INTO Questions (text) VALUES ('330. у меня никогда не было параличей или необычной слабости в мышцах рук, ног или других частей тела ');
INSERT INTO Questions (text) VALUES ('331. если бы люди не имели ничего против меня, я бы добился гораздо большего ');
INSERT INTO Questions (text) VALUES ('332. иногда у меня меняется или пропадает голос, даже если я не простужен ');
INSERT INTO Questions (text) VALUES ('333. мне кажется, что нет такого человека, который понимал бы меня ');
INSERT INTO Questions (text) VALUES ('334. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('335. мне трудно сосредоточить мысли на чем-то одном ');
INSERT INTO Questions (text) VALUES ('336. я легко теряю терпение с людьми ');
INSERT INTO Questions (text) VALUES ('337. я почти все время испытываю чувство тревоги за кого-то, или за что-то ');
INSERT INTO Questions (text) VALUES ('338. у меня безусловно больше причин для волнений, чем у других ');
INSERT INTO Questions (text) VALUES ('339. большую часть времени я желаю себе смерти ');
INSERT INTO Questions (text) VALUES ('340. иногда я бываю настолько возбужден, что мне трудно уснуть ');
INSERT INTO Questions (text) VALUES ('341. иногда я так хорошо слышу, что это мне мешает ');
INSERT INTO Questions (text) VALUES ('342. я сразу забываю то, что мне говорят ');
INSERT INTO Questions (text) VALUES ('343. я обычно должен остановиться и подумать, прежде чем сделать что-то, даже если речь идет о мелочах ');
INSERT INTO Questions (text) VALUES ('344. часто я перехожу на другую сторону улицы, чтобы не встретиться с тем, кого я увидел ');
INSERT INTO Questions (text) VALUES ('345. окружающее мне часто кажется нереальным ');
INSERT INTO Questions (text) VALUES ('346. у меня есть привычки считать ненужные предметы, такие как окна, лампочки, вывески и т.д. ');
INSERT INTO Questions (text) VALUES ('347. у меня нет врагов, которые бы всерьез хотели мне навредить ');
INSERT INTO Questions (text) VALUES ('348. меня настораживают люди, которые относятся ко мне более дружелюбно, чем я ожидал ');
INSERT INTO Questions (text) VALUES ('349. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('350. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('351. я становлюсь тревожным и расстроенным, когда приходится хотя бы ненадолго уехать из дома ');
INSERT INTO Questions (text) VALUES ('352. я боюсь некоторых предметов и людей, хотя знаю, что они мне не опасны ');
INSERT INTO Questions (text) VALUES ('353. я не боюсь войти в комнату, где уже собрались и разговаривают люди ');
INSERT INTO Questions (text) VALUES ('354. я боюсь пользоваться ножом или другими острыми предметами ');
INSERT INTO Questions (text) VALUES ('355. иногда мне бывает приятно причинить зло тем, кого я люблю ');
INSERT INTO Questions (text) VALUES ('356. мне труднее сосредоточиться, чем другим ');
INSERT INTO Questions (text) VALUES ('357. я не раз бросал какое-нибудь дело, так как считал, что не справлюсь с ним ');
INSERT INTO Questions (text) VALUES ('358. мне приходят в голову плохие, часто даже ужасные слова и я не могу от них избавиться ');
INSERT INTO Questions (text) VALUES ('359. иногда какая-нибудь маловажная мысль крутится в голове и надоедает мне нескольких дней подряд ');
INSERT INTO Questions (text) VALUES ('360. почти каждый день случается что-нибудь пугающее меня ');
INSERT INTO Questions (text) VALUES ('361. я склонен принимать все близко к сердцу ');
INSERT INTO Questions (text) VALUES ('362. я более обидчив, чем большинство людей ');
INSERT INTO Questions (text) VALUES ('363. иногда мне было приятно, если мне причинял страдания человек, которого я люблю ');
INSERT INTO Questions (text) VALUES ('364. люди говорят обо мне оскорбительные и пошлые вещи ');
INSERT INTO Questions (text) VALUES ('365. мне неспокойно, когда я нахожусь в закрытом помещении ');
INSERT INTO Questions (text) VALUES ('366. даже находясь среди людей, я большую часть времени чувствую себя одиноким ');
INSERT INTO Questions (text) VALUES ('367. я не боюсь огня ');
INSERT INTO Questions (text) VALUES ('368. иногда я стараюсь держаться дальше от людей, чтобы не сделать или не сказать что-либо, о чем потом буду жалеть ');
INSERT INTO Questions (text) VALUES ('369. вопросы религии меня не занимают ');
INSERT INTO Questions (text) VALUES ('370. ненавижу, когда я должен спешить в работе ');
INSERT INTO Questions (text) VALUES ('371. не могу сказать, что я чрезмерно застенчив ');
INSERT INTO Questions (text) VALUES ('372. я скорее склонен увлекаться многим, чем на долгое время остановиться на чем-то одном ');
INSERT INTO Questions (text) VALUES ('373. я уверен, что существует одно единственно правильное понимание смысла жизни ');
INSERT INTO Questions (text) VALUES ('374. временами мне кажется, что мой рассудок работает медленнее, чем обычно ');
INSERT INTO Questions (text) VALUES ('375. когда я чувствую себя счастливым и полным сил, кто-нибудь своим плохим настроением может все испортить ');
INSERT INTO Questions (text) VALUES ('376. милиционеры обычно - честные люди ');
INSERT INTO Questions (text) VALUES ('377. на вечеринке я чаще сижу один или беседую с одним из гостей, чем со всей группой ');
INSERT INTO Questions (text) VALUES ('378. мне нравится, когда женщина курит ');
INSERT INTO Questions (text) VALUES ('379. у меня редко бывают приступы плохого настроения ');
INSERT INTO Questions (text) VALUES ('380. когда кто-нибудь высказывает глупость или невежество в отношении известных мне вещей, я стараюсь его поправить ');
INSERT INTO Questions (text) VALUES ('381. мне часто говорят, что я вспыльчив ');
INSERT INTO Questions (text) VALUES ('382. хотелось бы мне избавиться от раздумий по поводу своих высказываний, которые, как мне кажется, могли кого- нибудь обидеть или огорчить ');
INSERT INTO Questions (text) VALUES ('383. люди часто разочаровывают меня ');
INSERT INTO Questions (text) VALUES ('384. я чувствую, что не смог бы рассказать кому-либо все о себе ');
INSERT INTO Questions (text) VALUES ('385. молния - одно из тех явлений, которые вызывают у меня страх ');
INSERT INTO Questions (text) VALUES ('386. я люблю держать людей в неведении относительно того, что собираюсь делать ');
INSERT INTO Questions (text) VALUES ('387. всякие чудеса я считаю только трюками, которые одни люди разыгрывают перед другими ');
INSERT INTO Questions (text) VALUES ('388. мне страшно быть одному в темноте ');
INSERT INTO Questions (text) VALUES ('389. мои планы нередко кажутся мне полными трудностей, из-за чего я отказываюсь от них ');
INSERT INTO Questions (text) VALUES ('390. меня часто неправильно понимают, когда я пытаюсь предостеречь кого- нибудь от ошибки, и это мне очень обидно ');
INSERT INTO Questions (text) VALUES ('391. я люблю ходить на такие вечера, где можно потанцевать ');
INSERT INTO Questions (text) VALUES ('392. буря вселяет в меня ужас ');
INSERT INTO Questions (text) VALUES ('393. лошадь, которая плохо везет, нужно бить ');
INSERT INTO Questions (text) VALUES ('394. я часто пользуюсь советами людей ');
INSERT INTO Questions (text) VALUES ('395. будущее слишком неопределенно, чтобы строить серьезные планы ');
INSERT INTO Questions (text) VALUES ('396. часто, даже если идут дела хорошо, я чувствую, что мне все безразлично ');
INSERT INTO Questions (text) VALUES ('397. у меня бывает такое чувство, что трудностей слишком много и нет смысла пытаться их преодолеть ');
INSERT INTO Questions (text) VALUES ('398. мне часто думается: "хорошо бы снова стать ребенком" ');
INSERT INTO Questions (text) VALUES ('399. меня трудно рассердить ');
INSERT INTO Questions (text) VALUES ('400. если бы позволили условия, я бы мог принести человечеству большую пользу ');
INSERT INTO Questions (text) VALUES ('401. я не испытываю страха перед водой ');
INSERT INTO Questions (text) VALUES ('402. чтобы прийти к решению вопроса, я часто откладываю его рассмотрение на завтра ');
INSERT INTO Questions (text) VALUES ('403. это великолепно - жить в наше время, когда происходит столько всяких интересных событий ');
INSERT INTO Questions (text) VALUES ('404. люди часто не понимают моих намерений, когда я пытаюсь поправить их или помочь им ');
INSERT INTO Questions (text) VALUES ('405. у меня нет затруднений при глотании ');
INSERT INTO Questions (text) VALUES ('406. мне часто приходилось встречать людей, которые считались специалистами, а на деле знали не больше моего ');
INSERT INTO Questions (text) VALUES ('407. обычно я спокоен и меня нелегко вывести из равновесия ');
INSERT INTO Questions (text) VALUES ('408. я склонен скрывать свои чувства из тех соображений, что люди невольно могут обидеть меня ');
INSERT INTO Questions (text) VALUES ('409. временами я изматываю себя тем, что берусь за слишком многое ');
INSERT INTO Questions (text) VALUES ('410. мне безусловно доставило бы удовольствие провести мошенника ');
INSERT INTO Questions (text) VALUES ('411. я чувствую себя неудачником, когда слышу об успехах знакомых мне людей ');
INSERT INTO Questions (text) VALUES ('412. я не боюсь обращаться к врачу, когда заболею или поранюсь ');
INSERT INTO Questions (text) VALUES ('413. я заслуживаю сурового наказания за свои проступки ');
INSERT INTO Questions (text) VALUES ('414. я склонен так остро переживать разочарование, что долго не могу выкинуть из головы ');
INSERT INTO Questions (text) VALUES ('415. при хорошем стечении обстоятельств я бы мог стать крупным хорошим руководителем ');
INSERT INTO Questions (text) VALUES ('416. мне не по себе, если кто-нибудь наблюдает, когда я работаю, даже если я знаю, что справлюсь со своим делом хорошо ');
INSERT INTO Questions (text) VALUES ('417. часто меня настолько раздражает субъект, пытающийся пролезть впереди меня без очереди, что я не премину ему это высказать ');
INSERT INTO Questions (text) VALUES ('418. временами мне кажется, что я ни на что не пригоден ');
INSERT INTO Questions (text) VALUES ('419. я часто прогуливал в школе ');
INSERT INTO Questions (text) VALUES ('420. мне случалось испытывать чрезвычайно необычные мистические переживания ');
INSERT INTO Questions (text) VALUES ('421. в моей семье есть очень нервные люди ');
INSERT INTO Questions (text) VALUES ('422. я испытываю неловкость за некоторых членов моей семьи из-за рода их работы ');
INSERT INTO Questions (text) VALUES ('423. я люблю (или любил раньше) рыбную ловлю ');
INSERT INTO Questions (text) VALUES ('424. большую часть времени я испытываю чувство голода ');
INSERT INTO Questions (text) VALUES ('425. я часто вижу сны ');
INSERT INTO Questions (text) VALUES ('426. временами я вынужден быть резким и грубым с раздражающими меня людьми ');
INSERT INTO Questions (text) VALUES ('427. меня смущают неприличные анекдоты ');
INSERT INTO Questions (text) VALUES ('428. мне нравится читать основополагающие статьи в газетах и журналах ');
INSERT INTO Questions (text) VALUES ('429. я люблю слушать лекции на серьезные темы ');
INSERT INTO Questions (text) VALUES ('430. меня влечет к лицам противоположного пола ');
INSERT INTO Questions (text) VALUES ('431. меня мало волнует возможность каких-нибудь неприятностей ');
INSERT INTO Questions (text) VALUES ('432. мои убеждения и взгляды непоколебимы ');
INSERT INTO Questions (text) VALUES ('433. я привык иметь воображаемого собеседника ');
INSERT INTO Questions (text) VALUES ('434. я бы хотел быть автогонщиком ');
INSERT INTO Questions (text) VALUES ('435. я предпочел бы работать с женщинами ');
INSERT INTO Questions (text) VALUES ('436. люди обычно требуют большего уважения к своим правам, чем сами уважают чужие ');
INSERT INTO Questions (text) VALUES ('437. вполне можно обойти закон, если вы этим его по существу не преступаете ');
INSERT INTO Questions (text) VALUES ('438. есть люди, которые мне настолько неприятны, что я внутренне радуюсь, когда они получают по заслугам ');
INSERT INTO Questions (text) VALUES ('439. я нервничаю, если приходится ждать ');
INSERT INTO Questions (text) VALUES ('440. я стараюсь запоминать интересные истории, чтобы потом рассказывать их другим ');
INSERT INTO Questions (text) VALUES ('441. мне нравятся высокие женщины ');
INSERT INTO Questions (text) VALUES ('442. у меня бывали периоды, когда я терял сон из-за волнений ');
INSERT INTO Questions (text) VALUES ('443. я готов отказаться от задуманного, если окружающие считают, что я начал это делать не так ');
INSERT INTO Questions (text) VALUES ('444. я не пытаюсь поправлять людей, которые высказывают ошибочные суждения ');
INSERT INTO Questions (text) VALUES ('445. в юности (или в детстве) я любил яркие, волнующие переживания ');
INSERT INTO Questions (text) VALUES ('446. я бы предпочел играть в карты, домино или другие игры на небольшую ставку ');
INSERT INTO Questions (text) VALUES ('447. я готов на все, чтобы победить в споре ');
INSERT INTO Questions (text) VALUES ('448. мне неприятно, если посторонние лица на улице, в магазине или в автобусе наблюдают за мной ');
INSERT INTO Questions (text) VALUES ('449. мне нравятся общественные мероприятия, где я могу побыть среди людей ');
INSERT INTO Questions (text) VALUES ('450. мне нравится волнение возбужденной толпы ');
INSERT INTO Questions (text) VALUES ('451. мои заботы исчезают, когда я попадаю в компанию веселых друзей ');
INSERT INTO Questions (text) VALUES ('452. я люблю подшучивать над людьми ');
INSERT INTO Questions (text) VALUES ('453. в детстве я не стремился быть членом уличной компании ');
INSERT INTO Questions (text) VALUES ('454. я бы мог жить счастливо один в избушке среди лесов и гор ');
INSERT INTO Questions (text) VALUES ('455. большей частью я не в курсе сплетен и разговоров окружающих меня людей ');
INSERT INTO Questions (text) VALUES ('456. не следует наказывать людей, нарушающих те законы, которые они считают неразумными ');
INSERT INTO Questions (text) VALUES ('457. я считаю, что люди никогда не должны прикасаться к спиртному ');
INSERT INTO Questions (text) VALUES ('458. мужчина, который больше всего занимался со мной в детстве (отец, отчим или другой человек), был со мной строг ');
INSERT INTO Questions (text) VALUES ('459. у меня есть одна (или более) дурная привычка, которая настолько сильна, что нет возможности с ней бороться ');
INSERT INTO Questions (text) VALUES ('460. я пью алкогольные напитки умеренно (или совсем не пью) ');
INSERT INTO Questions (text) VALUES ('461. мне трудно отложить начатую работу даже ненадолго ');
INSERT INTO Questions (text) VALUES ('462. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('463. я любил играть в "классы" или скакать через веревку ');
INSERT INTO Questions (text) VALUES ('464. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('465. мне не раз случалось менять свое отношение к своей профессии ');
INSERT INTO Questions (text) VALUES ('466. я никогда не принимаю лекарств или снотворных таблеток без назначений врача ');
INSERT INTO Questions (text) VALUES ('467. я часто запоминаю ненужные номера (например, номера машин) ');
INSERT INTO Questions (text) VALUES ('468. я часто жалею, что был таким упрямым и ворчливым ');
INSERT INTO Questions (text) VALUES ('469. я часто встречал людей, завидовавших моим идеям только потому, что они пришли в голову не им первым ');
INSERT INTO Questions (text) VALUES ('470. темы, связанные с половым вопросом, вызывают у меня отвращение ');
INSERT INTO Questions (text) VALUES ('471. мои отметки в школе систематически были плохими ');
INSERT INTO Questions (text) VALUES ('472. я испытываю непреодолимое влечение к огню ');
INSERT INTO Questions (text) VALUES ('473. по мере возможности я стараюсь избегать большого скопления людей ');
INSERT INTO Questions (text) VALUES ('474. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('475. оказавшись припертым к стене, я говорю лишь ту часть правды, которая мне не повредит ');
INSERT INTO Questions (text) VALUES ('476. я призван совершить великую миссию ');
INSERT INTO Questions (text) VALUES ('477. если бы я попал в беду вместе со своими друзьями, виновными в той же степени, что и я, я скорее предп очел бы взять всю вину на себя, чем выдать их ');
INSERT INTO Questions (text) VALUES ('478. я никогда особенно не волновался из-за неприятностей, которые случались с членами моей семьи ');
INSERT INTO Questions (text) VALUES ('479. я охотно знакомлюсь с новыми людьми ');
INSERT INTO Questions (text) VALUES ('480. я боюсь темноты ');
INSERT INTO Questions (text) VALUES ('481. бывали случаи, когда я притворялся больным, чтобы избежать чего-либо ');
INSERT INTO Questions (text) VALUES ('482. в трамваях, автобусах и т.д. я часто разговариваю с незнакомыми людьми ');
INSERT INTO Questions (text) VALUES ('483. я верю в чудеса ');
INSERT INTO Questions (text) VALUES ('484. у меня есть недостатки, которые настолько значительны, что лучше принять их как есть и пытаться контролировать, чем стараться искоренить ');
INSERT INTO Questions (text) VALUES ('485. мужчина, находясь в обществе женщин, обычно думает о вещах, связанных с ее полом ');
INSERT INTO Questions (text) VALUES ('486. я никогда не замечал крови в своей моче ');
INSERT INTO Questions (text) VALUES ('487. я быстро бросаю дело, если оно идет плохо ');
INSERT INTO Questions (text) VALUES ('488. я бы хотел, чтобы моя судьба была благосклонной ко мне ');
INSERT INTO Questions (text) VALUES ('489. я сочувствую людям, которые склонны застревать на своих бедах и огорчениях ');
INSERT INTO Questions (text) VALUES ('490. я люблю читать книги, помогающие правильно жить и понимать смысл жизни ');
INSERT INTO Questions (text) VALUES ('491. меня раздражают люди, которые считают, что их понимание смысла жизни единственно верное ');
INSERT INTO Questions (text) VALUES ('492. меня страшит мысль о возможности землетрясения ');
INSERT INTO Questions (text) VALUES ('493. я скорее предпочитаю работу, требующую пристального внимания, чем такую, при которой можно быть небрежным ');
INSERT INTO Questions (text) VALUES ('494. я боюсь находиться в маленьком закрытом помещении ');
INSERT INTO Questions (text) VALUES ('495. обычно я действую в открытую, если считаю важным поправить кого-нибудь ');
INSERT INTO Questions (text) VALUES ('496. у меня никогда не было двоения в глазах ');
INSERT INTO Questions (text) VALUES ('497. я люблю приключенческие рассказы ');
INSERT INTO Questions (text) VALUES ('498. лучше всегда говорить правду ');
INSERT INTO Questions (text) VALUES ('499. я должен признать, что временами волнуюсь без причины из-за того, что в действительности не имеет значения ');
INSERT INTO Questions (text) VALUES ('500. я готов на все ради хорошей идеи ');
INSERT INTO Questions (text) VALUES ('501. в работе я предпочитаю сам находить решение, а не следовать указаниям других ');
INSERT INTO Questions (text) VALUES ('502. я люблю, чтобы окружающие знали мое мнение ');
INSERT INTO Questions (text) VALUES ('503. я не склонен давать категорические оценки поступкам окружающих ');
INSERT INTO Questions (text) VALUES ('504. я не считаю нужным скрывать свое презрение или отрицательное мнение о ком-либо ');
INSERT INTO Questions (text) VALUES ('505. бывают периоды, когда я чувствую себя настолько полным сил, что казалось бы, мог обходиться без сна по несколько суток ');
INSERT INTO Questions (text) VALUES ('506. я человек нервный и легко возбудимый ');
INSERT INTO Questions (text) VALUES ('507. я часто работал под руководством таких людей, которые ставили себе в заслугу все достижения и сваливали все упущения и недостатки на подчинeнных ');
INSERT INTO Questions (text) VALUES ('508. думаю, что я различаю запахи так же хорошо, как другие ');
INSERT INTO Questions (text) VALUES ('509. иногда мне бывает трудно отстаивать свои права из-за моей сдержанности ');
INSERT INTO Questions (text) VALUES ('510. всякая грязь пугает меня или вызывает отвращение ');
INSERT INTO Questions (text) VALUES ('511. у меня есть мир мечтаний, о котором я никому не говорю ');
INSERT INTO Questions (text) VALUES ('512. я не люблю мыться в ванной ');
INSERT INTO Questions (text) VALUES ('513. мне больше нравится работать с руководителем, дающим строгие четкие указания, чем с руководителем, предоставляющим большую свободу ');
INSERT INTO Questions (text) VALUES ('514. мне нравятся мужеподобные женщины ');
INSERT INTO Questions (text) VALUES ('515. в моем доме всегда было все самое необходимое (достаточное количество еды, одежды и др.). ');
INSERT INTO Questions (text) VALUES ('516. у некоторых членов моей семьи вспыльчивый характер ');
INSERT INTO Questions (text) VALUES ('517. я ничего не могу сделать как следует ');
INSERT INTO Questions (text) VALUES ('518. я нередко испытываю чувство вины из-за того, что высказываю свое сочувствие людям в большей степени, чем на самом деле испытываю ');
INSERT INTO Questions (text) VALUES ('519. с моими половыми органами не все в порядке ');
INSERT INTO Questions (text) VALUES ('520. как правило, я твердо отстаиваю свое мнение ');
INSERT INTO Questions (text) VALUES ('521. я не смущаюсь в присутствии людей высказать свое мнение или вступить в спор по хорошо известному мне вопросу ');
INSERT INTO Questions (text) VALUES ('522. я не боюсь пауков ');
INSERT INTO Questions (text) VALUES ('523. я краснею очень редко ');
INSERT INTO Questions (text) VALUES ('524. я не боюсь заразиться какой-нибудь болезнью через дверные ручки ');
INSERT INTO Questions (text) VALUES ('525. некоторые животные приводят меня в содрогание ');
INSERT INTO Questions (text) VALUES ('526. будущее кажется мне безнадежным ');
INSERT INTO Questions (text) VALUES ('527. члены моей семьи и мои близкие родственники ладят друг с другом ');
INSERT INTO Questions (text) VALUES ('528. я краснею не чаще других ');
INSERT INTO Questions (text) VALUES ('529. мне нравится носить дорогую одежду ');
INSERT INTO Questions (text) VALUES ('530. я часто боюсь покраснеть ');
INSERT INTO Questions (text) VALUES ('531. люди легко могут изменить мое мнение, которое перед этим казалось мне окончательным ');
INSERT INTO Questions (text) VALUES ('532. я могу терпеть боль так же долго, как и другие ');
INSERT INTO Questions (text) VALUES ('533. у меня редко бывает отрыжка (или не бывает совсем) ');
INSERT INTO Questions (text) VALUES ('534. бывало, что я старался сделать что-то трудное тогда, когда все остальные уже отказались от дальнейших попыток ');
INSERT INTO Questions (text) VALUES ('535. у меня почти все время пересыхает во рту ');
INSERT INTO Questions (text) VALUES ('536. я сержусь, когда меня заставляют торопиться ');
INSERT INTO Questions (text) VALUES ('537. я бы хотел поохотиться на львов или тигров ');
INSERT INTO Questions (text) VALUES ('538. думаю, что мне бы понравилась работа портного по пошиву женского платья ');
INSERT INTO Questions (text) VALUES ('539. я не боюсь мышей ');
INSERT INTO Questions (text) VALUES ('540. у меня никогда не было парализовано лицо ');
INSERT INTO Questions (text) VALUES ('541. моя кожа необычайно чувствительна к прикосновению ');
INSERT INTO Questions (text) VALUES ('542. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('543. несколько раз в неделю у меня бывает чувство, что должно случиться что-то страшное ');
INSERT INTO Questions (text) VALUES ('544. я чувствую усталость большую часть времени ');
INSERT INTO Questions (text) VALUES ('545. иногда мне снится один и тот же сон ');
INSERT INTO Questions (text) VALUES ('546. я люблю читать историческую литературу ');
INSERT INTO Questions (text) VALUES ('547. я люблю бывать на вечерах и встречах ');
INSERT INTO Questions (text) VALUES ('548. я никогда не стану смотреть представления сексуального характера, если можно этого избежать ');
INSERT INTO Questions (text) VALUES ('549. я стараюсь избегать конфликтных и затруднительных положений ');
INSERT INTO Questions (text) VALUES ('550. мне нравится чинить дверные замки ');
INSERT INTO Questions (text) VALUES ('551. на этот вопрос ответьте "не знаю" ');
INSERT INTO Questions (text) VALUES ('552. я люблю читать о науке ');
INSERT INTO Questions (text) VALUES ('553. мне страшно быть одному на открытом со всех сторон месте ');
INSERT INTO Questions (text) VALUES ('554. если бы я был журналистом, я бы предпочел писать о театре ');
INSERT INTO Questions (text) VALUES ('555. иногда мне кажется, что я "на краю погибели" ');
INSERT INTO Questions (text) VALUES ('556. я очень внимателен в отношении стиля своей одежды ');
INSERT INTO Questions (text) VALUES ('557. мне бы понравилось работать секретарем ');
INSERT INTO Questions (text) VALUES ('558. большинство людей можно обвинить в плохом сексуальном поведении ');
INSERT INTO Questions (text) VALUES ('559. я часто испытываю страх среди ночи ');
INSERT INTO Questions (text) VALUES ('560. меня очень раздражает то, что я забываю, куда кладу вещи ');
INSERT INTO Questions (text) VALUES ('561. мне очень нравится верховая езда ');
INSERT INTO Questions (text) VALUES ('562. человеком, к которому я в детстве был больше всего привязан и кого я больше всех обожал, была женщина (мать, сестра, тетушка или др.). ');
INSERT INTO Questions (text) VALUES ('563. мне больше нравятся приключенческие повести, чем романтические ');
INSERT INTO Questions (text) VALUES ('564. я готов отказаться от своих намерений, если окружающие считают, что этого делать не стоит ');
INSERT INTO Questions (text) VALUES ('565. я испытываю желание прыгнуть вниз, когда нахожусь на высоте ');
INSERT INTO Questions (text) VALUES ('566. в кино я люблю смотреть любовные эпизоды. ');